# ============================================================
# API REST Completa del Sistema GIB - Cosmeticos Kitty
# Evidencia: GA7-220501096-AA5-EV03
# Aprendiz: Luz Adriana Alvarez Garcia - Ficha 3070319
# ============================================================

spring.application.name=gib-api-proyecto
server.port=8082

# Base de datos MySQL - stock_master_db
spring.datasource.url=jdbc:mysql://localhost:3306/stock_master_db?useSSL=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Formato de fechas en JSON
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.fail-on-empty-beans=false
